import { v4 as uuidv4 } from "uuid";
import { ProjectsData } from "./types";

const COPY_JOB_STEPS = [
  "Define what we are actually trying to copy",
  "Procure what we are trying to copy - more than 1!!",
  "Measure everything",
  "Material analysis",
  "Coating analysis",
  "Clearance and tolerance study",
  "Make drawings",
  "Make models",
  "Inspection plan for parts",
  "Measure original to our print (first)",
  "Update print to measurements",
  "Measure more parts (originals) to updated drawing",
  "Re-check tolerances",
  "Setup datum structure",
  "Test components on original - planned component test in logical way",
  "Define aftermarket accessories to be used",
  "Quote parts",
  "Can supplier measure parts?",
  "Supplier audit",
  "Drawing reviews with quality",
  "Inspection method per feature",
  "Inspection method with supplier",
  "Define gauges and fixturing needed for inspection",
  "Order prototype parts",
  "Review quotes",
  "Review supplier inspection plan",
  "Review supplier capabilities",
  "Incoming inspection",
  "Review certs",
  "Request certs",
  "Request inspection data",
  "Review FAI from vendor",
  "Review FAI from PSA",
  "Supplier feedback",
  "Deviation or drawing change",
  "Redo loop",
  "LRIP order",
  "Test parts",
  "Risk buy",
  "Test original parts on our gun",
  "Accessory/aftermarket compatibility test",
  "Get requirements",
  "Shoot competitor baseline (qualitative feedback)",
  "Launch quantity",
  "Competitor baseline quantitative feedback",
  "EV test on prototype",
  "Release proto drawings",
  "Release production drawings",
  "CAPEX",
  "Supplier selection meeting (more than just cost)",
  "DFM review per part with supplier",
  "Industrialization review",
  "Build production line",
  "Assembly drawing",
  "Manufacturing notes on assembly drawings",
  "Process drawings",
  "Build LRIP",
  "Design validation testing",
  "PV testing",
  "Redo loop 2",
  "Aesthetic signoff at EV",
  "Ergonomics signoff at EV",
  "Aesthetic signoff at DV",
  "Ergonomics signoff at DV",
  "Aesthetic signoff at PV",
  "Ergonomics signoff at PV",
  "Business case and signoff - OG and changes",
  "Requirements signoff - OG and changes",
  "Item setup in Netsuite",
  "Create BOM for SmartSheet",
  "Create BOM in Netsuite",
  "Pull part numbers in PDM",
  "Confirm launch skus",
  "Confirm launch SKU qty",
  "Confirm name",
  "Confirm marking variances",
  "Confirm assembly location",
  "Identify criticals",
  "Measure at EV",
  "Measure at DV",
  "Measure at PV",
  "Identify design lead, project manager, product manager and stick to it!",
  "Clear BOMs for testing",
  "Pre-test meeting",
  "Post-test meeting",
  "Create risk register",
  "Define accuracy requirement",
  "Define accuracy ammo",
  "Production test fire procedure",
  "Load demand in ERP",
  "Write manual",
  "Define packaging",
  "Cost roll",
  "Cost target",
  "Inventory transfer",
  "Website pictures",
  "Website page setup",
  "Videos pre release",
  "Post release videos",
  "Marketing gun build",
  "Product promotion guns (influencers, accessory mfgs, affiliates)",
  "Customer service training",
  "Warranty training",
  "Reseller training",
  "Production build",
  "Sustainment training",
  "Supplier update meetings",
  "Tooling review",
  "Tooling signoff",
  "Items costed for Netsuite",
  "Design reviews",
  "Drawing check",
  "Purchasing handoff",
  "End of line/in-process quality checks",
  "Production gauges",
  "Production fixtures",
  "Receive and distribute parts",
  "Update schedule weekly",
  "Cut test workorder",
  "Assembly line training",
  "Engineering presence for first builds",
  "Packaging label",
  "Exploded view",
  "Parts list",
  "Redo loop 3",
  "Alternative sourcing plans for secondary suppliers",
  "Project name",
];

const PROJECT_NAMES = [
  "Fully New",
  "Line Extension",
  "Component Changes",
  "Copy Job",
];

function createCards() {
  return COPY_JOB_STEPS.map((name, index) => ({
    id: uuidv4(),
    name,
    department: "",
    notes: "",
    sortOrder: index,
  }));
}

export function generateSeedData(): ProjectsData {
  return {
    projects: PROJECT_NAMES.map((name, index) => ({
      id: uuidv4(),
      name,
      sortOrder: index,
      cards: createCards(),
    })),
  };
}
